name: tese

channels:
  - conda-forge

dependencies:
  - python=3.9

  - numpy=1.24
  - pandas=1.5
  - scipy=1.10
  - scikit-learn=1.2

  - matplotlib=3.7
  - seaborn=0.12
  - ipympl
  - jupyter

  - geopandas=0.12
  - shapely=1.8
  - pyproj
  - fiona

  - openpyxl
  - ffmpeg
  - statsmodels
  - geodatasets

  - pip
  - pip:
      - ipyfilechooser
      - opencv-python-headless
      - pythermalcomfort
      - unidecode
      - contextily
      - biosppy
      - PeakUtils
      - git+https://github.com/emotional-cities/pluma-analysis.git@46cffe14b514d64a83483dbd07c93872ddc9577e